### ISSUE TITLE
Error on Create Change map on area changes tab in QGIS 2.8.3 using Molusce plugin

### ISSUE THREAD

**Issue by EMinja** [nextgis/molusce#47]
I am predicting the Land change using Molusce plugin but as i update table and create change map got the following error. the geometry of my raster are matched and all are in either signed or unsigned integers. 

An error has occured while executing Python code:

Traceback (most recent call last):
  File "C:/Users/MinJa/.qgis2/python/plugins\molusce\moluscedialog.py", line 467, in createChangeMap
    self.analyst = AreaAnalyst(self.inputs["initial"], self.inputs["final"])
  File "C:/Users/MinJa/.qgis2/python/plugins\molusce\algorithms\models\area_analysis\manager.py", line 62, in __init__
    raise AreaAnalizerError("List of categories of the first raster doesn't contains a category of the second raster!")
AreaAnalizerError

Python version:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]

QGIS version:
2.8.3-Wien Wien, 313a6bc

I will be very thankful if anyone can help me out to resolve the issue

**Comment by simgislab** [comment]
Try brand new MOLUSCE 4 for QGIS 3 and let us know if the problem persists

**Comment by ddddaus** [comment]
I got similar problem here. after updating the change table I can't create the change map. I already using both new and old MOLUSCE. Please help me :))


An error has occurred while executing Python code: 

AttributeError: 'NoneType' object has no attribute 'save' 
Traceback (most recent call last):
  File "C:\Users/duali/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\molusce\moluscedialog.py", line 598, in changeMapDone
    self.inputs["changeMap"].save(self.inputs["changeMapName"])
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'save'


Python version: 3.12.9 (main, Feb  7 2025, 14:34:44) [MSC v.1938 64 bit (AMD64)] 
QGIS version: 3.40.4-Bratislava Bratislava, 4dd7d7e969

**Comment by RemeshevskiyValeriy** [comment]
Hello @ddddaus! Could you please send your dataset to my email remeshevskiy@gmail.com, it will help to better understand the cause of the error.
